site_name: Machine Learning Investment Portfolio Strategy
site_description: From Strategy building to portfolio optimization, AI machine learning to fully automated algotrading
site_author: Your Name
site_url: https://forgetsomething.github.io/algotrading-strategy/

# Repository
repo_name: forgetsomething/algotrading-strategy
repo_url: https://github.com/forgetsomething/algotrading-strategy
edit_uri: edit/main/docs/

# Documentation directory
docs_dir: docs

# Configuration
theme:
  name: material
  language: en
  
  # Minimal palette to let custom CSS control styling
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Minimal features for clean ThinkBayes2 layout
  features:
    - search.highlight
    - search.suggest

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - meta
  - toc:
      permalink: true

# Extra JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra CSS
extra_css:
  - stylesheets/thinkbayes2.css

# Navigation
nav:
  - Algorithmic Trading Strategy: index.md
  - Front Matter:
    - Why Algorithmic Trading Matters: introduction/why-algo-trading.md
    - Book Structure Overview: introduction/book-structure.md
    - Who This Book is For: introduction/target-audience.md
  - Strategies:
    - "1. Trend Trading": strategies/trend-trading.md
    - "2. Mean Reversion": strategies/mean-reversion.md
    - "3. Statistical Arbitrage": strategies/statistical-arbitrage.md
    - "4. Only-Buy Portfolio": strategies/only-buy-portfolio.md
    - "5. Time Series Forecasting": strategies/time-series-forecasting.md
    - "6. Reinforcement Learning": strategies/reinforcement-learning.md
    - "7. Machine Learning Trading": strategies/ml-trading.md
    - "8. Market Trend Decision": strategy-development/preparation/market-trend-decision.md
    - "9. Regime Detection": strategy-development/preparation/regime-detection.md
    - "10. Backtesting Components": strategy-development/preparation/backtesting-components.md
    - "11. Single Stock Selection": strategy-development/instruments/single-stock.md
    - "12. Multiple Stocks": strategy-development/instruments/multiple-stocks.md
    - "13. ETF Index": strategy-development/instruments/etf-index.md
    - "14. Commodities": strategy-development/instruments/commodities.md
    - "15. Currency Pairs": strategy-development/instruments/currency-pairs.md
    - "16. Feature Selection": strategy-development/features/feature-selection.md
    - "17. Backtesting Timeframes": strategy-development/features/backtesting-timeframes.md
    - "18. Trading Frequency": strategy-development/features/trading-frequency.md
  - Optimization:
    - "19. GA, PSO, ES": optimization/single-objective/ga-pso-es.md
    - "20. NSGA-III": optimization/multi-objective/nsga3.md
    - "21. AGE-MOEA2": optimization/multi-objective/age-moea2.md
    - "22. DNSGA2": optimization/multi-objective/dnsga2.md
    - "23. SMS-EMOA": optimization/multi-objective/sms-emoa.md
    - "24. Multi-objective Portfolio": optimization/portfolio/multi-objective.md
    - "25. Deep Learning Portfolio": optimization/portfolio/deep-learning.md
    - "26. Optimization Tools": optimization/portfolio/tools.md
  - Risk Management:
    - "27. Kelly Criteria": management/cash/kelly-criteria.md
    - "28. 2% Rule": management/cash/two-percent-rule.md
    - "29. Model-based VaR": management/risk/model-based-var.md
    - "30. Rolling VaR": management/risk/rolling-var.md
    - "31. Pain Index": management/risk/pain-index.md
    - "32. Downside Risk": portfolio-risk/downside-risk.md

# Search
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Copyright
copyright: Copyright &copy; 2025 Your Name

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/python
      link: https://python.org
  generator: false
